/// NegPy `EXPOSURE_CONSTANTS` used by the S4a print curve (Neutral paper).
public enum ExposureConstants: Sendable {
    public static let densityMultiplier: Double = 0.2
    public static let anchorTargetDensity: Double = 0.75
    public static let assumedAnchor: Double = 0.46
    public static let isoRMin: Double = 50
    public static let isoRMax: Double = 180
    public static let slopeMin: Double = 2
    public static let slopeMax: Double = 10
    public static let dMax: Double = 2.3
    public static let dMin: Double = 0.06
    public static let toeShoulderStrength: Double = 0.85
    public static let toeSharpnessBase: Double = 6
    public static let shoulderSharpnessBase: Double = 3
    public static let toeShoulderWidthRef: Double = 2.5
    public static let toeHeight: Double = 0.90
    public static let shoulderHeight: Double = 0.35
    public static let gradeContrastScale: Double = 2.9
    public static let zoneDensitySharpness: Double = 4
    public static let zoneDensityShadowOffset: Double = 0.75
    public static let zoneDensityHighlightOffset: Double = -0.40
    public static let shadowNeutralPercentile: Double = 98
    public static let castRemovalMaxOffset: Double = 0.1
    public static let midtoneCastMaxOffset: Double = 0.2
    public static let neutralAxisCurvMaxRatio: Double = 0.45
    public static let paperMidtoneGamma: Double = 0.05
    public static let paperGammaWidth: Double = 0.6
    public static let toeGradeStrength: Double = 0.15 * 0.35 / 0.90
    public static let shoulderGradeStrength: Double = 0.12
    public static let autoGradeTarget: Double = 0.85
    public static let autoGradeNominalRange: Double = 0.9
    public static let autoGradeNominalRatio: Double = 1.5
    public static let autoGradeStrength: Double = 0.4
    public static let autoGradeMaxOverfill: Double = 1.2
    public static let activityBlock: Int = 8
    public static let activityGateDensity: Double = 0.05
    public static let activityMinFraction: Double = 0.05
    public static let anchorTrimClip: Double = 5
    public static let anchorMeterBand: Double = 0.12
    public static let anchorMeterStrength: Double = 0.2
    public static let texturalRangeClip: Double = 10
    public static let shadowReachPercentile: Double = 99
    public static let shadowReachDensity: Double = 1.9
    public static let highlightHoldPercentile: Double = 2
    public static let highlightHoldDensity: Double = 0.10
    public static let highlightHoldMax: Double = 0.5
    public static let cmyMaxDensity: Double = 0.2
    public static let lumaR: Double = 0.2126
    public static let lumaG: Double = 0.7152
    public static let lumaB: Double = 0.0722
    public static let neutralAxisHighlightBand: (Double, Double) = (0.10, 0.30)
    public static let neutralAxisMidBand: (Double, Double) = (0.40, 0.60)
    public static let neutralAxisShadowBand: (Double, Double) = (0.72, 0.92)
    public static let neutralAxisChromaQuantile: Double = 0.30
    public static let neutralAxisChromaCap: Double = 0.29
    public static let neutralAxisFirstPassCap: Double = 0.55
    public static let neutralAxisMinPixels: Int = 64
    public static let neutralAxisConfidenceN0: Double = 256
    public static let neutralAxisAgreementDeadzone: Double = 0.10
    public static let neutralAxisAgreementScale: Double = 0.20
}
